apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argooperatorrolebinding
  namespace: {{ .Release.Namespace | quote }}
subjects:
- kind: ServiceAccount
  name: huadmin
roleRef:
  kind: ClusterRole
  name: {{ template "argo-workflows.fullname" . }}-admin
  apiGroup: rbac.authorization.k8s.io